products/urls.py
from django.urls import path, include
from products.views import catalog, change_product, add_product, purchased, made_purchased, returned, returned_list, submit, reject

app_name = 'products'

urlpatterns = [
    path('catalog/', catalog, name='catalog'),
    path('change_product/<int:product_id>/',change_product, name='change_product'),
    path('add_product',add_product, name='add_product'),
    path('purchased/<int:product_id>/', purchased, name='purchased'),
    path('made_purchased/', made_purchased, name='made_purchased' ),
    path('returned/<int:purchase_id>/', returned, name='returned'),
    path('returned_list/', returned_list, name='returned_list'),
    path('submit/<int:returned_id>/', submit, name='submit'),
    path('reject/<int:returned_id>/', reject, name='reject'),
]

store/urls.py
from django.contrib import admin
from django.urls import path, include
from products.views import main
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', main, name='main' ),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, include
from users.views import login, registration, logout

app_name = 'users'

urlpatterns = [
    path('login/', login, name='login'),
    path('registration/', registration, name='registration'),
    path('logout/', logout, name= 'logout'),
]

products/models.py
from django.db import models
from users.models import User

class Products(models.Model):
    name = models.CharField(max_length=256)
    description = models.TextField()
    price = models.IntegerField()
    image = models.ImageField(upload_to='products_image',null=True, blank=True)
    quantity = models.PositiveIntegerField(default=0)

    class Meta:
        verbose_name = 'Product'
        verbose_name_plural = 'Products'

    def __str__(self):
        return f'Название: {self.name}'

class Purchase(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    product = models.ForeignKey(to=Products, on_delete=models.CASCADE)
    count = models.PositiveIntegerField(default=0)
    time_created = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return f'Пользователь: {self.user.username} | Товар: {self.product.name}'

class Return(models.Model):
    purchase = models.ForeignKey(to=Purchase, on_delete=models.CASCADE)
    time_created = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return f'Пользователь: {self.purchase.user.username} | Товар: {self.purchase.product.name}'

products/forms.py
from django import forms
from products.models import Products, Purchase, Return
from django.core.exceptions import ValidationError


class AddProductsForm(forms.ModelForm):
    class Meta:
        model = Products
        fields = ('name', 'description','price', 'image', 'quantity')

class ChangeProductsForm(forms.ModelForm):
    class Meta:
        model = Products
        fields = ('name', 'description','price', 'image', 'quantity')

class BuyProductsForm(forms.ModelForm):
    class Meta:
        model = Purchase
        fields = ('user','product', 'count')


    def clean(self):
        cleaned_data = super().clean()
        count = cleaned_data.get('count')
        product_quantity = self.cleaned_data.get('product').quantity 
        if count > product_quantity:
            raise ValidationError('There are not enough goods right now. Please, choose fewer goods.')
        return cleaned_data

##    def __init__(self, *args, **kwargs):
##        super(BuyProductsForm, self).__init__(*args, **kwargs)
##
##        for field_name, field in self.fields.items():
##           if field_name == 'count' or field_name == 'product':
##               continue  
##            field.widget.attrs['disabled'] = 'disabled'

class ReturnProductsForm(forms.ModelForm):
    class Meta:
        model = Return
        fields = ('purchase',)

products/views.py
from django.shortcuts import render, HttpResponseRedirect
from products.models import Products, Purchase, Return
from products.forms import AddProductsForm, ChangeProductsForm, BuyProductsForm, ReturnProductsForm
from django.urls import reverse
from users.models import User
from django.contrib import messages

def main(request):
    context = {'title': 'Главная страница'}
    return render(request, 'products/main.html', context)


def catalog(request):
    current_user = request.user
    initial_values = {
        'user': current_user,
    }
    form = BuyProductsForm(initial=initial_values)
    products = Products.objects.all()
    context = {
        'title': 'Каталог',
        'products': products,
        'form' : form,
        'initial_values': initial_values
    }
    return render(request, 'products/catalog.html', context)


def purchased(request, product_id):
    product = Products.objects.get(id=product_id)
    current_user = User.objects.get(username=request.user)
    if request.method == 'POST':
        form = BuyProductsForm(data=request.POST)
        if form.is_valid():
            product.quantity -= int(request.POST['count'])
            product.save()
            if current_user.wallet >= product.price * int(request.POST['count']):
                current_user.wallet -= product.price * int(request.POST['count'])
                current_user.save()
                form.save()
                messages.success(request, 'Товар был успешн куплен')
                return render(request, 'products/main.html')
            else:
                messages.error(request, "У вас недостаточно денег на счету!")
                return render(request, 'products/main.html')
    else:
        form = BuyProductsForm()
    
    context = {'product': product,  'form': form}
    return render(request, 'products/catalog.html', context)


def made_purchased(request):
    purchases = Purchase.objects.filter(user=request.user)
    form = ReturnProductsForm()
    context = {'purchases': purchases, 'form': form}
    return render(request, 'products/made_purchased.html', context)


def returned(request, purchase_id):
    purchase = Purchase.objects.get(id=purchase_id)
    if request.method == 'POST':
        form = ReturnProductsForm(data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('main'))
    else:
        form = ReturnProductsForm()
    context = {'form': form, 'purchase': purchase}
    return render(request, 'products/made_purchased.html', context)




def add_product(request):
    if request.method == 'POST':
        form = AddProductsForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('main'))
    else:
        form = AddProductsForm()
    context = {'form': form}
    return render(request, 'products/add_product.html', context)


def change_product(request, product_id):
    product = Products.objects.get(id=product_id)
    if request.method == 'POST':
        form = ChangeProductsForm(data=request.POST,  instance=product, files=request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('main'))
    else:
        form = ChangeProductsForm(instance=product)
    context = { 'title': 'Изменение товара',
                'product': product,
                'form': form,
                }
    return render(request, 'products/change_product.html', context)


def returned_list(request):
    returned_purchases = Return.objects.all()
    context = {'purchases': returned_purchases}
    return render(request, 'products/returned_list.html', context)

def submit(request, returned_id):
    returned_product = Return.objects.get(id=returned_id)
    purchase = Purchase.objects.get(product=returned_product.purchase.product)
    product = Products.objects.get(name=returned_product.purchase.product.name)
    user = User.objects.get(username=returned_product.purchase.user.username)
    if request.method == 'POST':
        product.quantity += returned_product.purchase.count
        product.save()
        user.wallet += product.price * purchase.count
        user.save()
        returned_product.delete()
        purchase.delete()

        return render(request, 'products/main.html')


def reject(request, returned_id):
    returned_product = Return.objects.get(id=returned_id)
    if request.method == 'POST':
        returned_product.delete()
        return render(request, 'products/main.html')

products/templates/products/add_product.html
{%extends 'products/base.html'%}
{%load static%}


{%block css%}
<link href="{% static 'vendor\css\add_product.css' %}" rel="stylesheet">
{%endblock%}

{%block content%}
<main>
    <h1>Добавление продукта</h1>
    <form action="{%url 'products:add_product'%}", method="post",  enctype="multipart/form-data">
        {% csrf_token %}
        <label for="productName">Название товара:</label>
        {{form.name}}

        <label for="productImage">Изображение товара (URL):</label>
        {{form.image}}

        <label for="productImage">Описание товара</label>
        {{form.description}}

        <label for="productQuantity">Количество в наличии:</label>
        {{form.quantity}}

        <label for="productPrice">Цена товара:</label>
        {{form.price}}

        <button type="submit">Добавить продукт</button>
    </form>
</main>
{%endblock%}

products/templates/products/base.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{title}}</title>
    {%block css%}{%endblock%}
</head>
<body>

<nav>
    {%if user.is_authenticated%}
    <a href="{%url 'products:catalog'%}">Начать покупки</a>
    <a href="{%url 'products:made_purchased'%}">Перейти к покупкам</a>
    <a href="{%url 'users:logout'%}">Выйти</a>
    {%if user.is_superuser%}
    <a href="{%url 'products:add_product'%}">Добавить товар</a>
    <a href="{%url 'admin:index'%}">Админ-панель</a>
    <a href="{%url 'products:returned_list'%}">Возврат товаров</a>
    {%endif%}
    {%else%}
    <a href="{%url 'products:catalog'%}">Начать покупки</a>
    <a href="{% url 'users:login' %}">Войти</a>
    <a href="{% url 'users:registration' %}">Зарегистрироваться</a>
    {%endif%}


</nav>
{%block content%}{%endblock%}
</body>
</html>

products/templates/products/catalog.html
{%extends 'products/base.html'%}
{%load static%}

    {%block css%}
    <link href="{% static 'vendor\css\catalog.css' %}" rel="stylesheet">
    {%endblock%}


{%block content%}
<main>
    <h1>Каталог товаров</h1>
    {%for product in products%}
    <div class="product">
            {%if product.image %}
            <img class="card-img-top"
                 src="{{product.image.url}}"
                 alt="">
            {%endif%}
        <div class="product-title">{{product.name}}</div>
        <div class="product-quantity">В наличии: {{product.quantity}}</div>
        <div class="product-price">Цена: {{product.price}} грн</div>
        {%if user.is_superuser%}
        <a href="{% url 'products:change_product' product.id %}" class="edit-link">Изменить товар</a>
        {%endif%}
        {%if not user.is_superuser and user.is_authenticated %}
        <form action="{%url 'products:purchased' product.id %}" , method="post">
            {% csrf_token %}
            <label for="username">колличество товаров</label>
            {{ form.as_p }}
        
            <button type="submit">подтвердить покупку</button>
        
        </form>
        
        {%endif%}
    </div>
    {%endfor%}

    <!-- Добавьте другие товары по аналогии -->

</main>
{%endblock%}

products/templates/products/change_product.html
{%extends 'products/base.html'%}
{%load static%}

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{title}}</title>
    {%block css%}
    <link href="{% static 'vendor\css\change_product.css' %}" rel="stylesheet">
    {%endblock%}

{%block content%}
<main>
    <h1>Редактирование продукта</h1>


    <form action="{%url 'products:change_product' product.id%}" method="post", enctype="multipart/form-data">
        {% csrf_token %}

        <label for="productName">Название товара:</label>
        {{form.name}}

        <label for="productName">Описание товара:</label>
        {{form.description}}

        <label for="productQuantity">Количество в наличии:</label>
        {{form.quantity}}

        <label for="productPrice">Цена товара:</label>
        {{form.price}}

        <div class="custom-file">
            {{form.image}}
            <label class="custom-file-label" >Выберите изображение</label>
        </div>

        <button type="submit">Применить изменения</button>
    </form>
    
{% if form.errors %}
<div>
    Ошибки в форме:
    <ul>
        {% for error in form.errors %}
            <li>{{ error }}</li>
        {% endfor %}
    </ul>
</div>
{% endif %}

</main>
{%endblock%}

products/templates/products/made_purchased.html
{%extends 'products/base.html'%}
{%load static%}

{%block css%}
    <link href="{% static 'vendor\css\made_purchased.css' %}" rel="stylesheet">
{%endblock%}


<main>
    <h1>Список приобретенных товаров</h1>
{%block content%}
    <table>
        {% for purchase in purchases %}
        <thead>
            <tr>
                <th>Товар: {{purchase.product.name}}</th>
                <th>Цена за единицу: {{purchase.product.price}}</th>
                <th>Приобретенное колличество: {{purchase.count}}</th>       
                <th><form action="{% url 'products:returned' purchase.id %}", method="post">
                    {% csrf_token %}
                    <label for="username">Товар: </label>
                    {{form.as_p }}
                    <button type="submit">подтвердить возврат</button>
                
                </form></th>  
                
            </tr>
        </thead>
        {% endfor %}

    </table>
</main>
{%endblock%}

products/templates/products/main.html
{%extends 'products/base.html'%}
{%load static%}

{%block css%}
    <link href="{% static 'vendor\css\main.css' %}" rel="stylesheet">
{%endblock%}

{%block content%}
<main>
    <h1>Abibas</h1>
    <h2>Мы рады приветствовать вас в нашем магазине одежды!</h2>
    <button id="start-purchase-btn" type="button" class="btn btn-lg">
        <a id="start-purchase-link" href="{% url 'products:catalog' %}">
            Каталог с товарами
        </a>
    </button>
    {% if messages %}
    <ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
</main>
{%endblock%}

products/templates/products/returned_list.html
{%extends 'products/base.html'%} {%load static%} {%block css%}
<link href="{% static 'vendor\css\returned_list.css' %}" rel="stylesheet" />
{%endblock%} {%block content%}
<table>
  {%for return in purchases%}
  <thead>
    <tr>
      <th>Товар:{{return.purchase.product.name}}</th>
      <th>Приобретенное колличество: {{return.purchase.count}}</th>
      <th>Пользователь:{{return.purchase.user.username}}</th>
      <th> <form action="{%url 'products:submit' return.id %}" method="post">
        {% csrf_token %}
         <button type="submit">Подтвердить</button>
    </form></th>
      <th> <form action="{%url 'products:reject' return.id %}" method="post">
        {% csrf_token %}
         <button type="submit">Отклонить</button>
    </form></th>
    </tr>
  </thead>
  {%endfor%}
</table>
{%endblock%}